# Rest and Sphinx Memo documentation build configuration file
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html
#
# All configuration values have a default; values that are commented out
# serve to show the default.
#
# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute.
#
import sys
import os
# sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, os.path.abspath('..'))

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'Rest and Sphinx Memo'
author = 'Marc Zonzon'
copyright = '2011-2024, ' + author


# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# extract versioning from git tags
from subprocess import Popen, PIPE
commit = Popen(["git", "describe","--tags", ], stdout=PIPE).communicate()[0]
commit = commit.decode().strip().split('-')

# The short X.Y version.
version = commit[0]
# The full version, including alpha/beta/rc tags.
release = '-'.join(commit)

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration
#
# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = [
    'sphinx.ext.autodoc', 'sphinx.ext.intersphinx', 'sphinx.ext.todo',
    'sphinx.ext.ifconfig', 'sphinx.ext.extlinks', 'sphinx.ext.imgmath',
    'sphinx.ext.graphviz', 'sphinx.ext.autosectionlabel']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# There are two options for replacing |today|: either, you set today to a non-empty
# value, it is used.  Otherwise, the current time is time.strftime() and the format
# given in today_fmt.
#
# today = ''
# today_fmt = '%b %d, %y'

# -- Options for internationalisation --------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-internationalisation
# The language for content autogenerated by Sphinx.
language = "en"

# -- Options for source files ----------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-source-files

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# These patterns also effect html_static_path and html_extra_path
exclude_patterns = ['include/**', 'code/*.rst']

# -- Options for markup --------------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-markup
# The reST default role (used for this markup: `text`) to use for all
# documents, can be customized by document with the default-role directive.
#
# default_role = None

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#
# show_authors = False

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False

# -- Options for object signature ------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-object-signatures
#
# add_function_parentheses = True

# -- Options for highlighting -----------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-highlighting
# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'
#pygments_style = 'monokai'

# Default highlight language, changed by highlight directive
# highlight_language = 'default'

# Options for python domain
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-the-python-domain

# add_module_names = True

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# manpages_url A URL to cross-reference manpage
# The patterns available are: page, section, path ( "page(section)")
manpages_url = "https://manpages.debian.org/{path}"

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

# on_rtd is whether we are on readthedocs.org
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'

# theme: one among 'default', 'bootstrap','cloud', 'sphinxtrap',
# 'readability', 'sphinx_rtd_theme'

theme = 'default'
if not on_rtd:
    theme = 'sphinx_rtd_theme'
if theme == 'cloud':
    import cloud_sptheme
elif theme == 'bootstrap':
    import sphinx_bootstrap_theme
elif theme == 'sphinxtrap':
    import sphinxtrap
elif theme == 'readability':
    import readability
elif theme == 'sphinx_rtd_theme':
    import sphinx_rtd_theme

# html_theme = 'default'
html_theme = theme

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
#html_theme_path = []
if theme == 'cloud':
    html_theme_path = [cloud_sptheme.get_theme_dir()]
elif theme == 'bootstrap':
    html_theme_path = sphinx_bootstrap_theme.get_html_theme_path()
elif theme == 'sphinxtrap':
    html_theme_path = [sphinxtrap.get_theme_dir()]
elif theme == 'readability':
    readability_path = os.path.dirname(os.path.abspath(sphinxtheme.__file__))
    relative_path = os.path.relpath(readability_path, os.path.abspath('.'))
    html_theme_path = [relative_path]
elif theme == 'sphinx_rtd_theme':
    html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

# The name for this set of Sphinx documents.
# "<project> v<release> documentation" by default.
#
# html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#
# html_short_title = None

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#
# html_logo = None

# The name of an image file (relative to this directory) to use as a favicon of
# the docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#
# html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#
# html_extra_path = []

# If not None, a 'Last updated on:' timestamp is inserted at every page
# bottom, using the given strftime format.
# The empty string is equivalent to '%b %d, %Y'.
#
# html_last_updated_fmt = None

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#
# html_additional_pages = {}

# If false, no module index is generated.
#
# html_domain_indices = True

# If false, no index is generated.
#
# html_use_index = True

# If true, the index is split into individual pages for each letter.
#
# html_split_index = False

# If true, links to the reST sources are added to the pages.
#
# html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#
# html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# html_search_language = language

# A dictionary with options for the search language support, empty by default.
# 'ja' uses this config value.
# 'zh' user can custom change `jieba` dictionary path.
#
# html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
#
# html_search_scorer = 'scorer.js'

# -- Options for HTMLHelp output ---------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-help-output

# Output file base name for HTML help builder.
htmlhelp_basename = 'RestSphinxMemodoc'


# -- Options for LaTeX output ------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-latex-output

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').

    'papersize': 'a4paper',

    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'RestSphinxMemo.ltx', project, author, 'manual'),
]

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#
# latex_use_parts = False

# If true, show page references after internal links.
#
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
#
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
#
# latex_appendices = []

# If false, no module index is generated.
#
# latex_domain_indices = True

# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'rest-sphinx-memo', project, [author], 1)
]

# If true, show URL addresses after external links.
#
# man_show_urls = False


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (startdocname, targetname, title, author, dir_entry, description, category,
# toctree_only)

texinfo_documents = [
  (master_doc, 'RestSphinxMemo', project, author, 'RestSphinxMemo', project,
   'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#
# texinfo_appendices = []

# If false, no module index is generated.
#
# texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#
# texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#
# texinfo_no_detailmenu = False

# -- Options for Epub output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-epub-output

# Bibliographic Dublin Core info.
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# The basename for the epub file. It defaults to the project name.
# epub_basename = project

# The HTML theme for the epub output. Since the default themes are not
# optimized for small screen space, using the same theme for HTML and epub
# output is usually not wise. This defaults to 'epub', a theme designed to save
# visual space.
#
# epub_theme = 'epub'

# The language of the text. It defaults to the language option
# or 'en' if the language is not set.
#
# epub_language = ''

# The scheme of the identifier. Typical schemes are ISBN or URL.
# epub_scheme = ''

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A tuple containing the cover image and cover page html template filenames.
#
# epub_cover = ()

# A list of CSS files. A filename string or a tuple containing the filename
# string and the attributes dictionary.
#
# epub_css_files = ()

# A sequence of (type, uri, title) tuples for the guide element of content.opf.
#
# epub_guide = ()

# HTML files that should be inserted before the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#
# epub_pre_files = []

# HTML files that should be inserted after the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#
# epub_post_files = []

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']

# The depth of the table of contents in toc.ncx.
#
# epub_tocdepth = 3

# Allow duplicate toc entries.
#
# epub_tocdup = True

# Choose between 'default' and 'includehidden'.
#
# epub_tocscope = 'default'

# Fix unsupported image types using the Pillow.
#
# epub_fix_images = False

# Scale large images.
#
# epub_max_image_width = 0

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#
# epub_show_urls = 'footnote'

# If false, no index is generated.
#
# epub_use_index = html_use_index

# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

intersphinx_mapping = {'python': ('https://docs.python.org/3', None)}

# -- Options for extlinks extension ---------------------------------------
# extlinks extension: https://www.sphinx-doc.org/en/master/usage/extensions/extlinks.html
# The second item in each tuple is the caption if it is None, the link caption is the
# full URL. if it is a string with on %s, the partial url is substituted to %s in the
# caption.
#
extlinks = {
    'sphinx': ('http://www.sphinx-doc.org/en/master/%s', 'Sphinx: %s'),
    'sphrst':  ('http://www.sphinx-doc.org/en/master/usage/restructuredtext/%s', 'Sphinx ReST %s'),
    'restref': ('http://docutils.sourceforge.net/docs/ref/rst/%s', 'ReST Référence: %s')
    }

# -- Options for todo --------------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/extensions/todo.html

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for GraphViz -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/extensions/graphviz.html

# place to set global graph, node or edge attributes via dot’s -G, -N and -E options.
# graphviz_dot_args = []

# "png" or "svg" with svg you need to specify the target in the graph
graphviz_output_format = "svg"

# I don't use autosectionlabel usually, only here for documenting the extension.
# option for autosectionlabel
autosectionlabel_prefix_document = True
